### PR TITLE
have bard-cli read whole prompt (or a part of it) from stdin

### PR DESCRIPTION
**Pull request by kirisakow**
see https://github.com/mosajjal/bard-cli/issues/27

### CODE REVIEW

**Comment by mosajjal** [comment]
looks good. I'm also keen to allow multiple `-f` options and append all of them in order. it could be part of this PR or a later one. up to you :)

**Review by mosajjal — CHANGES_REQUESTED** [review]
logic looks good. from the convention perspective, Python-style variable names (file_contents) are not really encouraged in Go.instead, local variables are camelCase (fileContents) small change but makes a difference in consistency.

**Comment by kirisakow** [comment]
> looks good. I'm also keen to allow multiple `-f` options and append all of them in order. it could be part of this PR or a later one. up to you :)

Thanks. I'm working on it. Please don't merge yet.

**Review by mosajjal — APPROVED** [review]

**Comment by mosajjal** [comment]
lgtm. good stuff mate :) closes #27

**Pull request merged**
