### PR TITLE
Grab cookies from Chrome

### PR DESCRIPTION
**Pull request by mosajjal**
- initial
- mvp

### CODE REVIEW

**Comment by kirisakow** [comment]
### First attempt, with a Chromium snap

```
$ go run . --getcookie # alternative: go build ; ./bard-cli --getcookie

2023-11-02T13:43:10+01:00 FTL Failed to retrieve cookies: chrome failed to start:
Gtk-Message: 13:43:10.673: Failed to load module "xapp-gtk3-module"
Gtk-Message: 13:43:10.674: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.

(chrome:85323): Gtk-WARNING **: 13:43:10.751: GTK+ module /snap/chromium/2673/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 13:43:10.751: Failed to load module "canberra-gtk-module"

(chrome:85323): Gtk-WARNING **: 13:43:10.752: GTK+ module /snap/chromium/2673/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Gtk-Message: 13:43:10.752: Failed to load module "canberra-gtk-module"
[85323:85323:1102/134310.777209:ERROR:process_singleton_posix.cc(335)] Failed to create /home/my_user/.config/google-chrome/SingletonLock: Permission denied (13)
[85323:85323:1102/134310.777270:ERROR:chrome_browser_main.cc(1505)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.

exit status 1
```

Notes to self:

* `Failed to load module "xapp-gtk3-module"`:
  * https://askubuntu.com/questions/1396739/failed-to-load-module-xapp-gtk3-module
  * `sudo apt install libxapp-gtk3-module`
    * successfully installed;
* `Failed to load module "canberra-gtk-module"`:
  * https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed
  * `sudo apt install libcanberra-gtk-module`
    * `libcanberra-gtk-module is already the newest version (0.30-10ubuntu4).`

<br>

### Second attempt, with a Chromium snap

```
$ go build ; ./bard-cli --getcookie

2023-11-04T17:06:05+01:00 FTL Failed to retrieve cookies: chrome failed to start:
[217726:217726:1104/170605.439711:ERROR:process_singleton_posix.cc(335)] Failed to create /home/my_user/.config/google-chrome/SingletonLock: Permission denied (13)
[217726:217726:1104/170605.439821:ERROR:chrome_main_delegate.cc(553)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.
```

**Comment by mosajjal** [comment]
@kirisakow let me know if it works fine and the cookies stay alive long enough. haven't tested this extensively myself.

**Comment by kirisakow** [comment]
I sense a weakness in that there are in fact many more various switch-cases than just `(darwin | windows | linux)`: there's also a `(chrome | chromium)` dilemma, and, for Ubuntu at least, the way it was installed: `(apt | flatpak | snap)`. In other words, too many cases for a sound algorithm to handle.

The solution may be to have the config file include

* path to the browser binary;

* path to user profile directory.

**Comment by mosajjal** [comment]
> I sense a weakness in that there are in fact many more various switch-cases than just `(darwin | windows | linux)`: there's also a `(chrome | chromium)` dilemma, and, for Ubuntu at least, the way it was installed: `(apt | flatpak | snap)`. In other words, too many cases for a sound algorithm to handle.
> 
> The solution may be to have the config file include
> 
>     * path to the browser binary;
> 
>     * path to user profile directory.

this should be covered [here](https://github.com/chromedp/chromedp/blob/b193297e042c86b7fe3cdcde2d91f39bf9a5a0f2/allocate.go#L349)?

**Comment by kirisakow** [comment]
> this should be covered [here](https://github.com/chromedp/chromedp/blob/b193297e042c86b7fe3cdcde2d91f39bf9a5a0f2/allocate.go#L349)?

Thank you. Indeed, it is — as far as the path to the binary is concerned. 

As for the path to user profile directory: I completely uninstalled my Chromium —and I did it twice, the second time with manually removing the `~/.config/google-chrome/` directory; then I reinstalled Chromium (twice, yeah). Nothing helped.

Then I replaced [browser.go, line 29](https://github.com/mosajjal/bard-cli/pull/36/files#diff-0796d1f3ad3beb70c454de3c6ce14004126a6f0648655fc649422336e0517bc2R29)
```go
chromeProfilePath = filepath.Join(usr.HomeDir, `.config/google-chrome/`)
```
with this path [I showed you earlier](https://github.com/mosajjal/bard-cli/issues/30#issuecomment-1775042162):
```go
chromeProfilePath = filepath.Join(usr.HomeDir, `snap/chromium/common/chromium/`)
```

Only in that way did it work.

With `chromeProfilePath` changed, running bard-cli with the `--getcookie` option prints out the three cookie values as it should:

```
$ go build ; ./bard-cli --getcookie
cookie1psid: (...).
cookie1psidts: sidts-(...)
cookie1psidcc: ACA-(...)
2023-11-06T15:35:19+01:00 INF copy the above lines to your ~/.bardcli.yaml file
```

I still think the user should provide the path to their profile as a setting in the config file.

**Comment by kirisakow** [comment]
There is another issue:

### Retrieving cookies fails if there is an open instance of Chromium

```
$ go build ; ./bard-cli --getcookie
2023-11-06T15:43:48+01:00 FTL Failed to retrieve cookies: chrome failed to start:
Opening in existing browser session.
```

Shouldn't `bard-cli` be able to retrieve those cookies no matter what?

**Comment by kirisakow** [comment]
Oh and since we're at it, there have been a few dependency updates in the meantime.

**Comment by mosajjal** [comment]
a few points here:
- to your point, profile folder should become an optional parameter. 
- dependencies are OS-level not Go-level, just need to add a paragraph in the README to document them.
- opening an existing session should be an option but not a super high priority. I'm happy to push the changes with the limitation of "only new browser windows" and fix it later.

**Comment by kirisakow** [comment]
> * to your point, profile folder should become an optional parameter.
Yeah, it seems like a good idea to me.

The hypothetical use case could be the following:
1. The user tries to launch bard-cli with the option `--getcookie`.
2. Say, execution fails. The error message should include a suggestion for the user to specify the path to the profile directory in the config file.
3. As long as that setting is specified in the config file, that setting overrides the default hardcoded path. (**NB:** Actually, now that I'm thinking about it, the default hardcoded path should probably not be hardcoded but specified in the config file from the moment the user runs `bard-cli --defaultconfig`.)

**Comment by kirisakow** [comment]
> * dependencies are OS-level not Go-level, just need to add a paragraph in the README to document them.

I meant the dependencies in the `go.mod` and `go.sum` files. It seems like there have been a few updates out there.

**Comment by kirisakow** [comment]
> * opening an existing session should be an option but not a super high priority. I'm happy to push the changes with the limitation of "only new browser windows" and fix it later.

Sure, go ahead

**Pull request closed without merging**
